### ISSUE TITLE
现在这个是每行4个item，如果改成3个 那个滑动的动画就有问题了！

### ISSUE THREAD

**Issue by MIkeeJY** [Guolei1130/DragGridView#2]
之前在CSDN 看到过跟这个很相似的 那个也一样是4个item的  但是改成3个的时候 位移动画的偏移量就会有问题~

**Comment by MIkeeJY** [comment]
拖动之后的  位移动画会闪动不像每行4个的时候那样平滑

**Comment by Guolei1130** [comment]
您好，我建议您使用RecyclerView+ItemTouchHelper去实现，参考https://github.com/Guolei1130/DragRecyclerView或者网上的其他例子，如果非要用GridView的话，请修改下面代码。

不过，强烈建议别用GridView，麻烦，bug多。

if (i  % 4 == 0){
                //
                to_x = x_vlaue \* 3;
                to_y = -y_vlaue;
            }else {
                to_x = -x_vlaue;
                to_y = 0;
            }
            Log.e("tag","这是移动参数--->"+to_x+";"+to_y);
            ViewGroup moveViewGroup = (ViewGroup) getChildAt(i);
            Animation moveAnimation = getMoveAnimation(to_x, to_y);
            moveViewGroup.startAnimation(moveAnimation);
